### ISSUE TITLE
Add a List of MEPs

### ISSUE THREAD

**Issue by YoKoGFX** [Insax/savetheinternet#116]
We should add a list of the MEPs like they did on https://saveyourinternet.eu
Maybe we should also display contact infos on hover for the specific persons.

**Comment by RealPolluX** [comment]
![image](https://user-images.githubusercontent.com/12788936/41509349-bb4ae092-7252-11e8-808e-6701f66f3c59.png)

current progress

**Comment by NLDev** [comment]
This is very similar to an already existing issue: https://github.com/Insax/savetheinternet/issues/63
Which is already done: https://github.com/Insax/savetheinternet/pull/136
