### ISSUE TITLE
Gallery broken

### ISSUE THREAD

**Issue by kellerrennkadse** [Insax/savetheinternet#132]
On live and dev, the gallery is broken due to a JavaScript error (moment.js is missing)

**Comment by aytic** [comment]
```
Attempted to load class "Imagick" from the global namespace.  
  Did you forget a "use" statement?    
```

need help

**Comment by NLDev** [comment]
Semi-Fixed now. The images not loading was not due to a JS error. 
That was because of a PHP failure. 
The module `php-imagick` did not render the thumbnails. 

The gallery however still remains broken. At least the layout does.
