### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by accard** [Insax/savetheinternet#144]
Die yaml file muss eingefügt werden

---

The yaml file needs to be added

**Comment by NLDev** [comment]
Translation:
[messages.sw_SW.txt](https://github.com/Insax/savetheinternet/files/2109504/messages.sw_SW.txt)

**Comment by aytic** [comment]
There is still some german in the file and I think the article_content lacks the part which is written in the html tags to link to the pdf

article_content: 'Den 20e Juni röstar den lagliga kommittén av EU-parlamentet på det föreslågna <a href="https://eur-lex.europa.eu/legal-content/DE/TXT/PDF/?uri=CELEX:52016PC0593&from=EN" class="highlight">Urheberrechts-Richtlinie</a> ab. De enda som kan stoppa denna dödliga lag nu är medlemmarna av Europaparlamentet !'


# Footer section
about_link: 'Info'
imprint_link: 'Impressum'
privacy_link: 'Privacy Policy'

**Comment by aytic** [comment]
I pushed the current status to dev
