### ISSUE TITLE
MEP Selection mobile version

### ISSUE THREAD

**Issue by kellerrennkadse** [Insax/savetheinternet#147]
The selection of MEPs should have a good mobile solution

**Comment by NLDev** [comment]
Just was about to open the exact same issue ^^

**Comment by kellerrennkadse** [comment]
Guess we saw the same post linking to the dev page?

**Comment by NLDev** [comment]
Welp, I made that post :p

**Comment by NLDev** [comment]
Fixed with https://github.com/Insax/savetheinternet/pull/149

**Comment by NLDev** [comment]
https://github.com/Insax/savetheinternet/pull/152
