### ISSUE TITLE
MEP Mail/Twitter icons fuzzy

### ISSUE THREAD

**Issue by kellerrennkadse** [Insax/savetheinternet#158]
![image](https://user-images.githubusercontent.com/40218022/41548584-aadb0dbe-7323-11e8-9864-39e60a592482.png)

They are a bit fuzzy because the BG is stretched in a weird way.

**Comment by NLDev** [comment]
Yes, the images actually look like that: https://github.com/Insax/savetheinternet/blob/master/assets/static/mep/tweet-bg.png

If someone from Media could make a new background, that would be awesome!

**Comment by NLDev** [comment]
Fixed: https://github.com/Insax/savetheinternet/pull/172
