### ISSUE TITLE
Write to your deputy! Buttons don't work properly

### ISSUE THREAD

**Issue by Ronja11** [Insax/savetheinternet#160]
- There are no ready-made messages.
- Clicking on the Twitter button opens the Twitter page of the person. But when you click on the E-Mail button nothing happens.

**Comment by kellerrennkadse** [comment]
Well, we don't have any ready-made messages we could insert here...

**Comment by Ronja11** [comment]
Well I have no idea. I thought it maybe would appear if the Mail Button
would work properly.

kellerrennkadse <notifications@github.com> schrieb am Mo., 18. Juni 2018,
23:37:

**Comment by kellerrennkadse** [comment]
Also, clicking on the mail button opens your default Mailhandler and inserts the address of the MEP as the recipient. We could add a subject line and a default body stub, but

1. You guessed it, we don't have text for that either
2. Adding default text might cause people to send that default text stub, and making an MEP read through hundreds of duplicate mails won't cause them to change their opinion

I agree with you.. we should add _some_ help to write a message, but we need help of texters and translators

**Comment by Ronja11** [comment]
Hmm, okay. On my computer nothing opens, but it seems to be a problem on my
side if it works in general.

I initially mentioned a text sample, because the text on the site says that
there are "ready-made messages". And yes I think it would be useful. But
your are right, if there are no texts yet, more people would be needed to
create something like this. And it also would probably take too long.
So maybe the best option ist to delete the part on the website saying there
are samples? (to prevent irritation)

kellerrennkadse <notifications@github.com> schrieb am Mo., 18. Juni 2018,
23:43:

**Comment by kellerrennkadse** [comment]
Yep, we should probably delete that. I'll have to hand that to the translate team tomorrow, since I can't figure out what to remove in languages other than german or english..

**Comment by Ronja11** [comment]
Same here ^^ - thanks!

kellerrennkadse <notifications@github.com> schrieb am Di., 19. Juni 2018,
00:30:
