### ISSUE TITLE
!!Urgent!! ready-made messages are missing on the Site !!Urgent!!

### ISSUE THREAD

**Issue by hcosoft** [Insax/savetheinternet#163]
![grafik](https://user-images.githubusercontent.com/11291928/41553548-5c12d586-7332-11e8-945c-5dff6edcf502.png)

Please Fix immediatly

**Comment by hcosoft** [comment]
No this is not fixed, im talking about the ready made messages, these are not implemented! Yes, i will see a list, but the Text is still missing. This is Urgent, because we are advertising to write to the Deputy but are not offering the text!

**Comment by RealPolluX** [comment]
I will have a look into this. But messages should be implemented as mentioned above.

**Comment by NLDev** [comment]
This won't be implemented I think. 

https://github.com/Insax/savetheinternet/issues/160#issuecomment-398215756

Also, from what I've heard, its best to write a custom text and not spam the MEP with ready made stuff. 
That doesn't help anyone...
