### ISSUE TITLE
Put icons over the text

### ISSUE THREAD

**Issue by YoKoGFX** [Insax/savetheinternet#165]
<img width="464" alt="bildschirmfoto 2018-06-18 um 20 47 36" src="https://user-images.githubusercontent.com/18743976/41555760-f8c2b846-7338-11e8-9f50-8e352ef4ac1b.png">
We should put the Icons over the text, this looks very bad.

**Comment by FlorianMaak** [comment]
We should keep them in place. The only option (my opinion) could be a position on the left side of the headline.

**Comment by kellerrennkadse** [comment]
> The only option (my opinion) could be a position on the left side of the headline.

yea.. I'd prefer them to not be centered aswell, primarily on mobile where the text gets really long
