### ISSUE TITLE
Show link to the livestream (if the countdown goes to 0)

### ISSUE THREAD

**Issue by aytic** [Insax/savetheinternet#166]
Can be replaced/integrated in the countdown section
http://www.europarl.europa.eu/ep-live/de/committees/video?event=20180620-0900-COMMITTEE-JURI

**Comment by kellerrennkadse** [comment]
Now that we have to review how we handle privacy stuff (#159 )

**Comment by FlorianMaak** [comment]
Any specifications about how to display the video?
Is this feature already approved by coordination team (or other responsibles)?

**Comment by kellerrennkadse** [comment]
Guess it's not approved yet. But we could get the approval once horsthansen or someone from PR is here.

On the how to display part.. Visually the same as the german video we have on the page already, but with a disclaimer about privacy first.

We need a text for that though, and it only needs to be active in Germany

**Comment by kellerrennkadse** [comment]
Anyhow.. can we include the livestream? Are we legally allowed to? 
The easiest way is probably to link to the official stream?

**Comment by FlorianMaak** [comment]
The legal-question is a good one - i have no idea. This is something we need to check first.

**Comment by RealPolluX** [comment]
We still can link it! :)
