### ISSUE TITLE
Add missing translations for the "Select country" button

### ISSUE THREAD

**Issue by YoKoGFX** [Insax/savetheinternet#179]
We need to add translations for the "Select country" button. We currently have English and German, all other Pages are using English translations.

**Comment by stehlegg** [comment]
Choisissez le pays        Französich
Selectați țara      Rumänisch

**Comment by stehlegg** [comment]
Wybierz kraj / polnisch

**Comment by stehlegg** [comment]
Elija su país     Spanisch

**Comment by FlorianMaak** [comment]
Added with https://github.com/Insax/savetheinternet/pull/186
