### ISSUE TITLE
Video Embed

### ISSUE THREAD

**Issue by Insax** [Insax/savetheinternet#26]
Add a css + js for a pretty video embed.

**Comment by kellerrennkadse** [comment]
To prevent too much traffic from piling up.. maybe host it on vimeo or thelike?

**Comment by ThermalCube** [comment]
@kellerrennkadse Wouldn't this reintroduce the issue with third-party cookies?

**Comment by kellerrennkadse** [comment]
Not if you ask for consent before inserting the video into the page. I'm doing that sh*t at work right now.

You basically replace the video with a frame that asks the user to allow embedding a video, with a link to the privacyterms page. We could even use the one I just got sent from the company lawyer

**Comment by Insax** [comment]
Would also be a possibility, vimeo would be fine i guess, because i really just want to avoid youtube (for obv reasons)

**Comment by kellerrennkadse** [comment]
Fuck D:
Kümmere ich mich heute abend drum..

**Comment by kellerrennkadse** [comment]
Because it's unnecessary load, and depending on how many ppl watch the video at once, we might have the bandwith, but at some point there are other limitations such as concurrent connections, diskspeed, ...

Let vimeo handle that shit for us:

Also: I'm almost done.
