### ISSUE TITLE
Add gallery page for flyers

### ISSUE THREAD

**Issue by ThermalCube** [Insax/savetheinternet#28]
https://codepen.io/mican/pen/awxmpY
versus
https://codepen.io/mican/pen/RyjZgm

**Comment by kellerrennkadse** [comment]
New Requirements:

- [ ] Scan folder for Images and PDFs
- [ ] List them on the page
- [ ] Main gallery on its own page
- [ ] Put some teaser images with a link to the gallery on tha landing 


Maybe split galleries into memes/general stuff

**Comment by NLDev** [comment]
https://github.com/Insax/savetheinternet/pull/101
