### ISSUE TITLE
Twitterfeed changes

### ISSUE THREAD

**Issue by Insax** [Insax/savetheinternet#45]
2 columns -> maybe seprated with a seperator
5 rows
 adjust color to background
destroy old items and attach new one's above

**Comment by FlorianMaak** [comment]
I think we need to fix the order of tweets. (Newest on top)
Currently they're a bit mixed up^^

**Comment by kellerrennkadse** [comment]
Do we really? Is it necessary to have them in order?

**Comment by FlorianMaak** [comment]
I think so. It's a bit confusing, if you see "1min ago" at first position, "1 day ago" on second and "3min ago" at third. (Just examples)

**Comment by aytic** [comment]
I made a change to the script. Maybe this is resolved now
