### ISSUE TITLE
Add section for all planned demos

### ISSUE THREAD

**Issue by Insax** [Insax/savetheinternet#59]
Add subsection below the WHAT CAN YOU DO section for regional demo info

Day
Location
Time

2 coloms, x needed lines

**Comment by kellerrennkadse** [comment]
any text above or just the info?

**Comment by aytic** [comment]
PR wants to have a section on the page where you can see a google maps (or other) where a user can add demo locations and times (no validation requirement as he wants to use the number of demos for pr)

**Comment by FlorianMaak** [comment]
This would need a backend-endpoint to store and recive  demos. Is somebody already working on this? 

How to implement this?
* Map on the left and a list of demos on the right side (a click will move the map to the demos position)
* Map on the left and Infos about the current selection on the right? (User needs to select a demo. As a default I would select the nearest demo)

Any ideas about the add-form?
* modal dialog
* inside the right column
* single page
