### ISSUE TITLE
Translate About Page

### ISSUE THREAD

**Issue by kellerrennkadse** [Insax/savetheinternet#61]
add about / info page with longer texts (for better explanation)
use the texts from the petition (change.org)

(i.A. von FieseFliese)

**Comment by kellerrennkadse** [comment]
Texte können aus der Petition von change.org übernommen werden

**Comment by aytic** [comment]
FieseFliese - Today at 11:30 AM
die petition kann man nicht in verschiedenen sprachen gestalten
wir lassen sie auf englisch, den deutschen text für die website kriegst du von mir
The Red Panda of BitConnect - Today at 11:31 AM
ok
FieseFliese - Today at 11:55 AM
https://savetheinternet.piratenpad.de/22
hier sollen alle übersetzungen drinstehen

**Comment by RealPolluX** [comment]
1) We're missing an italian translation for now.
2) We also do need another text block for the "Wikipedia and Github" part.

@Text is working on point 2 for now

**Comment by RealPolluX** [comment]
possibility to add danish translation also given, but all other parts of the page missing there

**Comment by aytic** [comment]
I will rename this to translate about page since the implementation has been done

**Comment by RealPolluX** [comment]
text block exchanged already, added french & danish translations

now only italian translation is missing, spanish would also be a plus

**Comment by RealPolluX** [comment]
also spanish translation added now.
