### ISSUE TITLE
Mail to memer of parlament list 

### ISSUE THREAD

**Issue by NLDev** [Insax/savetheinternet#63]
Implementation of a JSON Filter to select land & region and get results based on those options.

http://www.europarl.europa.eu/meps/de/full-list.html?filter=all&leg=

https://pastebin.com/QjAFN0MC

**Comment by ThermalCube** [comment]
I would suggest view/lens approach with RandaJs

**Comment by NLDev** [comment]
Update: I took the list from 

https://voxscientia.eu/meps/

See branch https://github.com/Insax/savetheinternet/tree/country-list-2

**Comment by NLDev** [comment]
https://github.com/Insax/savetheinternet/pull/136
