### ISSUE TITLE
Save the Internet Logo goes into Navbar on Mobile

### ISSUE THREAD

**Issue by YoKoGFX** [Insax/savetheinternet#69]
On a Viewpoint of 568px (width) the Dynamic Logo goes into the Navbar.
<img width="460" alt="bildschirmfoto 2018-06-15 um 15 57 44" src="https://user-images.githubusercontent.com/18743976/41471822-f36fd9b8-70b4-11e8-8a1f-d7d1a3c9d6b4.png">

**Comment by kellerrennkadse** [comment]
We will fix this, but got some more urgent things in the pipeline right now

**Comment by aytic** [comment]
Seems you tested that on devtools. Please confirm this issue on a real device. Cannot replicate on 1 iPhone and 3 Android phones
