### ISSUE TITLE
Translation of highlited words

### ISSUE THREAD

**Issue by NLDev** [Insax/savetheinternet#72]
The way the highlighted words are currently built in does not work for all languages.

For english and german, the words are always at the end. See here:

https://github.com/Insax/savetheinternet/blob/master/templates/index/components/article-thirteen.html.twig#L38-L39

But for other languages such as french, the word would be somewhere in the middle of the sentence. 
That's a problem on the template side.

**Comment by kellerrennkadse** [comment]
Fix is already known. Use the highlight tag directly in the translation file, just like here:

https://github.com/Insax/savetheinternet/blob/master/translations/messages.it_IT.yml#L21
