### ISSUE TITLE
Website nicht so Meme-Spezifiziert machen

### ISSUE THREAD

**Issue by Chaaaaaaaaarlie** [Insax/savetheinternet#73]
Wie wäre es, wenn auf der Website etwas mehr auf den allgemeinen Benutzer eingegangen wird? Zum Beispiel dass auch die Snapchatstory bei Mecces, das Instagrambild von Kinotickets/Plakaten etc. betroffen wären. Sonst denken die Randomuser halt einfach: "Memes? Juckt ja keinen, solange ich noch auf Insta posten kann was ich will..." - Nur ein Vorschlag was für dazu einfallen würde, wenn ich mal ganz objektiv die Seite anschaue und mein Hirn ausschalte sehe ich halt nur die Schlagwörter "Diktatur, Links, Memes" und den Timer etwas weiter unten, danach ist das Interesse schon erloschen - benz0n

**Comment by kellerrennkadse** [comment]
Guter input, aber dafür fehlen uns Texte und Co. Wenn du das was organisieren kannst nehmen wir das gerne mit rein

**Comment by Chaaaaaaaaarlie** [comment]
War nur Ausrichter des Kommentars 🤷‍♂️ 
Gebe ich so weiter, wenn er wieder da ist.

**Comment by NLDev** [comment]
Is this still a WIP?

**Comment by NLDev** [comment]
Guess not. Closing for now...
