### ISSUE TITLE
[Backend] JSON-API related to locations

### ISSUE THREAD

**Issue by FlorianMaak** [Insax/savetheinternet#93]
Related Issue: https://github.com/Insax/savetheinternet/issues/59

I talked to horsthansen, how this feature should be implemented. 
He told me, that users should be able to submit own demonstration-locations and times.

__So we need two backend-endpoints:__
* accept a POST-Request and store data into database
* a GET-Request, providing stored demo-date, submitted by users

# Example POST-Requestbody
(float) lat: -25.363
(float) lng: 131.044
(string) title: "Titel der Demo"
(integer) timestamp: 1529097399 

# Example GET-Response
```json
[
{"lat": -25.363, "lng": 131.044, "title": "Titel der Demo", "timestamp": 1529097399 },
{"lat": -25.363, "lng": 131.044, "title": "Titel der Demo", "timestamp": 1529097399 },
{"lat": -25.363, "lng": 131.044, "title": "Titel der Demo", "timestamp": 1529097399 }
]
```

**Comment by fionera** [comment]
Backend part complete

https://github.com/Insax/savetheinternet/tree/map-backend

**Comment by FlorianMaak** [comment]
Feature removed!
