### ISSUE TITLE
Add Download link for Flyers in Color & B/W

### ISSUE THREAD

**Issue by mesk0ne** [Insax/savetheinternet#94]
to main page: 

Bunt : https://github.com/NoSpread/eu_media/blob/master/Freigegeben/Flyer/4x6/ILLEGAL-4x.pdf

B/W : https://github.com/NoSpread/eu_media/blob/master/Freigegeben/Flyer/4x6/flyer_illegal_4x.pdf

Sind finale Versionen der Flyer und kann so verwendet werden.
S/W Flyer wird noch einmal für einen Besseren Kontrast überarbeitet aber der LINK bleibt gleich !!!  wurde mit Medienteam so abgesprochen.

**Comment by kellerrennkadse** [comment]
Duplicate of #28
